//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 09:44:45 PM MSK 
//


package com.mikovic.demoshopinternet.gener;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mikovic.demoshopinternet.gener package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mikovic.demoshopinternet.gener
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBasketRequest }
     * 
     */
    public GetBasketRequest createGetBasketRequest() {
        return new GetBasketRequest();
    }

    /**
     * Create an instance of {@link GetBasketResponse }
     * 
     */
    public GetBasketResponse createGetBasketResponse() {
        return new GetBasketResponse();
    }

    /**
     * Create an instance of {@link Basket }
     * 
     */
    public Basket createBasket() {
        return new Basket();
    }

}
